# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Francis Wang's blog
email: wangyanq@gmail.com
description: > # This is Frank Wang's blog, this blog focus on docker, python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frankwang.cn"
# the base hostname & protocol for your site
twitter_username: yanqiw
github_username: yanqiw

# Build settings
markdown: kramdown

#theme
theme: just-the-docs
logo: "/assets/images/just-the-docs.png"

# Aux links for the upper right navigation
aux_links:
  "Github":
    - "//www.github.com/yanqiw"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
